#development:
#  dialect: postgres
#  datasource: dbname=test sslmode=disable user=accessControl password=agryz2010 host=localhost
#  dir: migrations
#  table: migrations

development:
    dialect: sqlite3
    datasource: test.db
    dir: migrations